let JSON_COLONNE = '{ "columns" : ['
               + '{ "0":"compilatoreEmail" , "title":"Compiler email" },'
               + '{ "1":"dataRegistrazione" , "title":"Registration date" , "width":"10%"},'
               + '{ "2":"compilatoreCognome" , "title":"Lastname compiler" },'
               + '{ "3":"compilatoreNome", "title":"Name compiler" },'
               + '{ "4":"compilatoreCognomeNome" , "title":"Compiler" },'
               + '{ "5":"statusItem","title":"Status Item" },'
               + '{ "6":"eliminatoreEmail" , "title":"Eliminator email" },'
               + '{ "7":"dataEliminazione" , "title":"Date of elimination", "type": "date" },'
               + '{ "8":"operatoreUltimoAggiornamento" , "title":"Operator last updtare" },'
               + '{ "9":"dataUltimoAggiornamento" , "title":"Last update date", "type": "date" },'
               + '{ "10":"vehicleNumber" , "title":"Vehicle Number" },'
               + '{ "11":"richiedenteEmail" , "title": "Driver email" },'
               + '{ "12":"richiedenteCognome" , "title":"Driver lastname" },'
               + '{ "13":"richiedenteNome" , "title":"Driver name" },'
               + '{ "14":"richiedenteCognomeNome" , "title":"Driver" },'
               + '{ "15":"chilomentriPrevisti" , "title":"Expected kilometers" , "width":"10%" },'
               + '{ "16":"causale" , "title":"Motivation" },'
               + '{ "17":"dataPrelievo" , "title":"Pick-up date" },'
               + '{ "18":"dataRestituzionePrevista" , "title":"Pick-up return", "type":"date-uk" },'
               + '{ "19":"destinazione" , "title":"Destination"},'
               + '{ "20":"ente" , "title":"Company name"},'
               + '{ "21":"opzioniveicolo" , "title":"Vehicle option" , "width":"3%" },'
               + '{ "22":"oraprelievo" , "title":"Pick-up time" , "width":"3%" },'
               + '{ "23":"orarestituzione", "title":"Return time" , "width":"3%" },'
               + '{ "24":"passeggeri" , "title":"Number of passengers" , "width":"3%" },'
               + '{ "25":"nomePasseggeri" , "title":"Passengers name" },'
               + '{ "26":"tipoVeicolo" , "title":"Vehicle type" , "width":"4%"},'
               + '{ "27":"autorizzatoreEmail" , "title":"Authorizer email" },'
               + '{ "28":"autorizzazioneStato" , "title":"Authorization status" },'
               + '{ "29":"dataAutorizzazione" , "title":"Date of authorization" , "type":"date"},'
               + '{ "30":"targa" , "title":"License plate" },'
               + '{ "31":"assegnazioneStato" , "title":"State assignment" },'
               + '{ "32":"assegnatoreEmail" , "title":"Assigner email" },'
               + '{ "33":"assegnazioneMyCard" , "title":"MyCard" }, '
               + '{ "34":"assegnazioneData" , "title":"Assigner date" , "type":"date" },'
               + '{ "35":"restituzioneStato" , "title":"Return status" },'
               + '{ "36":"dataRestituzione" , "title":"Return date" , "type":"date" },' 
               + '{ "37":"chilometriAllArrivo" , "title":"Kilometers to arrival" },'
               + '{ "38":"serbatoio" , "title":"Tank status" },'
               + '{ "39":"danni" , "title":"Damage" },'
               + '{ "40":"descrizioneDanni" , "title":"Damage description" },'
               + '{ "41":"Note" , "title":"Note" },'
               + '{ "42":"Check","title":"" , "orderable":false , "className": "select-checkbox", "width": "2%"}]}';
